# states.py

NEQUI_MENU, NEQUI_NAME, NEQUI_NUMBER, NEQUI_AMOUNT, NEQUI_COMERCIO_NAME, NEQUI_COMERCIO_AMOUNT, BANCOLOMBIA_MENU, BANCOLOMBIA_NUMBER, BANCOLOMBIA_AMOUNT = range(9)



#7116486757:AAHpLB8iEZCPa4kFZft6jx_mBVwTmHz4eT8
#upward-prawn-stunning.ngrok-free.app/7116486757:AAHpLB8iEZCPa4kFZft6jx_mBVwTmHz4eT8